<script setup>
import { ref } from 'vue'
import { rereviewApi } from '../../api/rereviewApi'
const props=defineProps({reviewId:{type:[String,Number],required:true}});const emit=defineEmits(['created'])
const revised=ref();const response=ref();const language=ref('AUTO');const loading=ref(false);const error=ref('')
function pick(event,kind){const file=event.target.files?.[0];if(!file)return;if(file.type!=='application/pdf'||!file.name.toLowerCase().endsWith('.pdf')||file.size>20*1024*1024){error.value='Both files must be PDFs no larger than 20 MB.';return}if(kind==='revised')revised.value=file;else response.value=file;error.value=''}
async function submit(){loading.value=true;error.value='';try{const made=await rereviewApi.create(props.reviewId,revised.value,response.value,language.value);const done=await rereviewApi.start(made.rereviewId||made.id);emit('created',done)}catch(e){error.value=e.message}finally{loading.value=false}}
</script>
<template><form class="rereview-form panel" @submit.prevent="submit"><div><p class="eyebrow">VERIFICATION REVIEW</p><h2>Check the revision, claim by claim.</h2><p class="muted">Upload the revised manuscript and the author response letter as PDFs.</p></div><label>Revised manuscript<input type="file" accept="application/pdf,.pdf" required @change="pick($event,'revised')"><small v-if="revised">{{ revised.name }}</small></label><label>Response to reviewers<input type="file" accept="application/pdf,.pdf" required @change="pick($event,'response')"><small v-if="response">{{ response.name }}</small></label><label>Output language<select v-model="language"><option value="AUTO">Match paper</option><option value="zh">中文</option><option value="en">English</option></select></label><p v-if="error" class="error">{{ error }}</p><button class="primary" :disabled="!revised||!response||loading">{{ loading?'Verifying revisions…':'Start verification review' }}</button></form></template>
<style scoped>.rereview-form{display:grid;gap:20px;max-width:760px}.rereview-form label{padding:14px;border:1px solid #d9d7ce;border-radius:9px}.rereview-form input[type=file]{border:0;padding:9px 0}.rereview-form small{color:#607068}.rereview-form .primary{justify-self:start}</style>
