package com.paper.reviewer.stream.domain;

public enum ReviewEventType {
    PAPER_UPLOADED,
    PDF_EXTRACTING,
    PDF_EXTRACTED,
    FIELD_ANALYSIS_STARTED,
    FIELD_ANALYSIS_COMPLETED,
    REVIEWER_TEAM_GENERATED,
    REVIEWER_TEAM_CONFIRMED,
    FULL_REVIEW_STARTED,
    QUICK_REVIEW_STARTED,
    REREVIEW_STARTED,
    REVIEWER_REPORT_STARTED,
    REVIEWER_REPORT_DELTA,
    REVIEWER_REPORT_COMPLETED,
    EDITORIAL_DECISION_STARTED,
    REVISION_ROADMAP_STARTED,
    AUTHOR_QUESTIONS_STARTED,
    REVIEW_COMPLETED,
    REVIEW_FAILED,
    EXPORT_COMPLETED
}
