<script setup>
import { onMounted, ref } from 'vue'
import { dashboardApi } from '../api/dashboardApi'
const dashboard=ref({paperCount:0,reviewCount:0,activeReviewCount:0,completedReviewCount:0,recentReviews:[]});const loading=ref(true);const error=ref('')
onMounted(async()=>{try{dashboard.value=await dashboardApi.get()}catch(e){error.value=e.message}finally{loading.value=false}})
function date(value){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium'}).format(new Date(value)):''}
</script>
<template><section><p class="eyebrow">OVERVIEW</p><h1>Good work starts with a clear read.</h1><div class="actions"><router-link class="primary button" to="/upload">Upload a paper</router-link><router-link class="secondary button" to="/history">Browse history</router-link></div><p v-if="error" class="error">{{ error }}</p><div v-if="loading" class="panel">Loading your workspace…</div><template v-else><section class="metrics" aria-label="Workspace summary"><article><span>Papers</span><strong>{{ dashboard.paperCount }}</strong></article><article><span>All reviews</span><strong>{{ dashboard.reviewCount }}</strong></article><article><span>In progress</span><strong>{{ dashboard.activeReviewCount }}</strong></article><article><span>Completed</span><strong>{{ dashboard.completedReviewCount }}</strong></article></section><section class="panel activity"><header><div><p class="eyebrow">LATEST ACTIVITY</p><h2>Recent reviews</h2></div><router-link to="/history">View all records →</router-link></header><div v-if="!dashboard.recentReviews?.length" class="empty"><span>∅</span><p>No reviews yet. Upload a paper to begin.</p></div><router-link v-for="review in dashboard.recentReviews" :key="review.reviewId" class="row" :to="`/reviews/${review.reviewId}`"><div><strong>{{ review.paperTitle }}</strong><small>{{ review.reviewType }} · {{ date(review.createdAt) }}</small></div><span :class="`status status-${review.status?.toLowerCase()}`">{{ review.status }}</span></router-link></section></template></section></template>
<style scoped>.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:20px}.metrics article{display:grid;gap:12px;padding:22px;background:var(--paper);border:1px solid var(--line);border-radius:12px}.metrics span{color:var(--muted);font-size:.8rem}.metrics strong{font:600 2.6rem 'Newsreader',serif;color:var(--pine)}.activity{margin-top:0;min-height:300px}.activity header{display:flex;justify-content:space-between;align-items:end;margin-bottom:24px}.activity header .eyebrow{margin-bottom:9px}.activity header a{color:var(--pine);font-size:.88rem}.row{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:17px 4px;border-top:1px solid #e4e2da;text-decoration:none;border-radius:6px}.row:hover{background:#f4f3ed}.row div{display:grid;gap:5px}.row small{color:#737b75;font-size:.78rem}.status{padding:5px 9px;border-radius:999px;background:#ecebe5;color:#59615b;font-size:.72rem}.status-completed{background:#e1eee6;color:#245f43}.status-failed{background:#f8e7e2;color:#a2372c}.empty{display:grid;place-items:center;text-align:center;color:#778078;min-height:180px}.empty span{font-size:2rem}@media(max-width:800px){.metrics{grid-template-columns:1fr 1fr}}@media(max-width:480px){.metrics{grid-template-columns:1fr}.activity header{align-items:flex-start;gap:18px}}</style>
