<script setup>
import { onMounted, ref } from 'vue'
import { useRouter } from 'vue-router'
import { reviewApi } from '../api/reviewApi'
import { paperApi } from '../api/paperApi'
import ConfirmDialog from '../components/common/ConfirmDialog.vue'
const router=useRouter();const reviews=ref([]);const loading=ref(true);const deleting=ref(false);const pendingDelete=ref(null);const error=ref('')
async function load(){loading.value=true;error.value='';try{const r=await reviewApi.list();const records=r.items||r.content||r;if(records.some(item=>!item.paperTitle)){const p=await paperApi.list();const papers=p.items||p.content||p;const titles=new Map(papers.map(item=>[item.id||item.paperId,item.title||item.originalFilename]));reviews.value=records.map(item=>({...item,paperTitle:item.paperTitle||titles.get(item.paperId)}))}else reviews.value=records}catch(e){error.value=e.message}finally{loading.value=false}}
function askDelete(review){pendingDelete.value=review}
async function confirmDelete(){if(!pendingDelete.value)return;deleting.value=true;error.value='';try{await reviewApi.remove(pendingDelete.value.id||pendingDelete.value.reviewId);pendingDelete.value=null;await load()}catch(e){error.value=e.message}finally{deleting.value=false}}
function openReview(review){router.push(`/reviews/${review.id||review.reviewId}`)}
function date(value){return value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):''}
onMounted(load)
</script>
<template><section><p class="eyebrow">HISTORY</p><h1>Your review history.</h1><p v-if="error" class="error">{{ error }}</p><div v-if="loading" class="panel">Loading review records…</div><section v-else class="panel history-list"><p v-if="!reviews.length" class="muted">No review records yet.</p><article v-for="review in reviews" :key="review.id||review.reviewId" class="history-row" role="link" tabindex="0" @click="openReview(review)" @keydown.enter="openReview(review)"><div class="record"><strong>{{ review.paperTitle||'Untitled paper' }}</strong><span>{{ review.reviewType }} · {{ review.status }} · {{ date(review.createdAt) }}</span></div><div class="actions"><router-link v-if="review.status==='COMPLETED'" class="text-link" :to="`/upload?sourceReview=${review.id||review.reviewId}`" @click.stop>Re-review</router-link><button class="danger" @click.stop="askDelete(review)">Delete</button><span class="arrow" aria-hidden="true">→</span></div></article></section><ConfirmDialog :open="Boolean(pendingDelete)" title="Delete this review?" :message="`The ${pendingDelete?.reviewType||''} review for “${pendingDelete?.paperTitle||'this paper'}” and all exported files will be permanently deleted.`" :busy="deleting" @cancel="pendingDelete=null" @confirm="confirmDelete"/></section></template>
<style scoped>.history-list{margin-top:44px;padding-top:8px}.history-row{display:flex;justify-content:space-between;align-items:center;gap:20px;padding:20px 8px;border-top:1px solid #e2e0d8;cursor:pointer;border-radius:6px}.history-row:hover,.history-row:focus{background:#f4f3ed;outline:none}.record{display:grid;gap:6px}.record strong{font-size:1.05rem}.history-row span{color:#747c76;font-size:.82rem}.actions{display:flex;gap:14px;align-items:center}.danger{border:0;background:none;color:#a23c35;cursor:pointer}.text-link{color:#174b38;font-size:.85rem}.arrow{font-size:1.2rem!important;color:#174b38!important}@media(max-width:650px){.history-row{align-items:flex-start}.actions{flex-wrap:wrap;justify-content:flex-end}.record span{line-height:1.5}}</style>
