<script setup>
import { onMounted, reactive, ref } from 'vue'
import { settingsApi } from '../api/settingsApi'
const form = reactive({ email:'', displayName:'', defaultOutputLanguage:'AUTO', provider:'qwen', model:'' }); const loading=ref(true); const saving=ref(false); const message=ref(''); const error=ref('')
onMounted(async()=>{ try{Object.assign(form,await settingsApi.get())}catch(e){error.value=e.message}finally{loading.value=false} })
async function save(){saving.value=true;error.value='';message.value='';try{Object.assign(form,await settingsApi.update({displayName:form.displayName,defaultOutputLanguage:form.defaultOutputLanguage}));message.value='Preferences saved.'}catch(e){error.value=e.message}finally{saving.value=false}}
</script>
<template><section><p class="eyebrow">PREFERENCES</p><h1>Settings.</h1><div v-if="loading" class="panel">Loading preferences…</div><form v-else class="settings panel" @submit.prevent="save"><div><h2>Account</h2><p class="muted">Your private workspace identity.</p></div><label>Email<input :value="form.email" disabled></label><label>Display name<input v-model="form.displayName" maxlength="100" required></label><label>Default review language<select v-model="form.defaultOutputLanguage"><option value="AUTO">Match paper</option><option value="zh">中文</option><option value="en">English</option></select></label><div class="model-card"><span class="model-dot"/><div><strong>Qwen · {{ form.model || 'system default' }}</strong><p>Managed globally by the server. OpenAI adapter: reserved.</p></div></div><p v-if="error" class="error">{{ error }}</p><p v-if="message" class="success">{{ message }}</p><button class="primary" :disabled="saving">{{ saving?'Saving…':'Save preferences' }}</button></form></section></template>
<style scoped>.settings{max-width:680px;display:grid;gap:22px}.settings label{max-width:460px}.model-card{display:flex;gap:12px;align-items:center;background:#e9eee8;padding:16px;border-radius:10px}.model-card p{margin:2px 0 0;color:#677069;font-size:.85rem}.model-dot{width:10px;height:10px;border-radius:50%;background:#28a76a;box-shadow:0 0 0 5px #28a76a22}.settings .primary{justify-self:start}.success{color:#17643c}</style>
